//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWcfTest")]
public interface IWcfTest
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfTest/GetNum", ReplyAction="http://tempuri.org/IWcfTest/GetNumResponse")]
    int GetNum();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWcfTestChannel : IWcfTest, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WcfTestClient : System.ServiceModel.ClientBase<IWcfTest>, IWcfTest
{
    
    public WcfTestClient()
    {
    }
    
    public WcfTestClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WcfTestClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WcfTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WcfTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetNum()
    {
        return base.Channel.GetNum();
    }
}
